// <auto-generated />
namespace Laboratorio.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBLaboratorio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBLaboratorio));
        
        string IMigrationMetadata.Id
        {
            get { return "202305141706331_DBLaboratorio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
